# Generated by Django 5.2 on 2025-04-10 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_expensesource_business_revenuesource_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('interval_in_days', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='expensesource',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revenuesource',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensesource',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.currency'),
        ),
        migrations.AddField(
            model_name='revenuesource',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.currency'),
        ),
        migrations.AddField(
            model_name='expensesource',
            name='frequency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.frequency'),
        ),
        migrations.AddField(
            model_name='revenuesource',
            name='frequency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.frequency'),
        ),
    ]
