# Generated by Django 5.2 on 2025-04-19 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_currency_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.currency'),
        ),
    ]
